Completed part 1.
GeneraStudios/PFMCPP_Project1 pull request #1
Opened 2020-09-09 17:52 UTC by GeneraStudios

Completed part 1 on replit.

2020-09-09 23:47 UTC, matkatmusic requested changes

2020-09-09 23:47 UTC, matkatmusic commented on main.cpp
> +gun.recoil();
As explained in the instructions, here is the obligatory request for some changes to get you familiar with the Pull Request Review process.
**replace** the highlighted noun/action as follows:
- [ ] come up with a new noun and 3 actions
- [ ] pick a noun that needs `camelCase` for the name
- [ ] pick actions that need `camelCase` for their name.

2020-09-10 03:24 UTC, GeneraStudios commented
Changes incorporated.

2020-09-10 04:07 UTC, matkatmusic approved these changes

2020-09-10 04:07 UTC, merged